/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.projeto2.barelanchonete.view;

import br.com.projeto2.barelanchonete.model.Produto;
import java.util.ArrayList;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sluiz
 */
public class GUIMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIMenu.class.getName());

    /**
     * Creates new form GUIMenu
     */
    public GUIMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jInternalFrameCadastroProduto = new javax.swing.JInternalFrame();
        jLabelCadastroProdutoNome = new javax.swing.JLabel();
        jTextFieldCadastroProdutoNome = new javax.swing.JTextField();
        jLabelCadastroProdutopreco = new javax.swing.JLabel();
        jTextFieldCadastroProdutoPreco = new javax.swing.JTextField();
        jButtonCadastroProdutoSalvar = new javax.swing.JButton();
        jButtonCadastroProdutoCancelar = new javax.swing.JButton();
        jInternalFramePesquisar = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePesquisarPorNome = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxPesquisarAcao = new javax.swing.JComboBox<>();
        jTextFieldPesquisarID = new javax.swing.JTextField();
        jButtonPesquisarConfirmar = new javax.swing.JButton();
        jButtonPesquisarCancelar = new javax.swing.JButton();
        jLabelPesquisarQuantidade = new javax.swing.JLabel();
        jTextFieldPesquizarQuantidade = new javax.swing.JTextField();
        jInternalFrameEditarCadastro = new javax.swing.JInternalFrame();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldEditarNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldEditarPreco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEditarId = new javax.swing.JTextField();
        jButtonEditarSalvar = new javax.swing.JButton();
        jButtonEditarCancelar = new javax.swing.JButton();
        jMenuBarPrincipal = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemCadastroProduto = new javax.swing.JMenuItem();
        jMenuEdicao = new javax.swing.JMenu();
        jMenuItemEdicaoProduto = new javax.swing.JMenuItem();
        jMenuPesquisar = new javax.swing.JMenu();
        jMenuItemPesquisarProduto = new javax.swing.JMenuItem();
        jMenuVendas = new javax.swing.JMenu();
        jMenuItemVendasCarrinho = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Bar e Lanchonete");

        jInternalFrameCadastroProduto.setBackground(new java.awt.Color(0, 51, 255));
        jInternalFrameCadastroProduto.setTitle("Cadastro de Produto");
        jInternalFrameCadastroProduto.setVisible(true);

        jLabelCadastroProdutoNome.setText("Nome do Produto");

        jLabelCadastroProdutopreco.setText("Preço");

        jButtonCadastroProdutoSalvar.setText("Salvar");
        jButtonCadastroProdutoSalvar.addActionListener(this::jButtonCadastroProdutoSalvarActionPerformed);

        jButtonCadastroProdutoCancelar.setText("Cancelar");
        jButtonCadastroProdutoCancelar.addActionListener(this::jButtonCadastroProdutoCancelarActionPerformed);

        javax.swing.GroupLayout jInternalFrameCadastroProdutoLayout = new javax.swing.GroupLayout(jInternalFrameCadastroProduto.getContentPane());
        jInternalFrameCadastroProduto.getContentPane().setLayout(jInternalFrameCadastroProdutoLayout);
        jInternalFrameCadastroProdutoLayout.setHorizontalGroup(
            jInternalFrameCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameCadastroProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrameCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jInternalFrameCadastroProdutoLayout.createSequentialGroup()
                        .addComponent(jButtonCadastroProdutoSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCadastroProdutoCancelar))
                    .addGroup(jInternalFrameCadastroProdutoLayout.createSequentialGroup()
                        .addGroup(jInternalFrameCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCadastroProdutoNome)
                            .addComponent(jLabelCadastroProdutopreco))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrameCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCadastroProdutoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCadastroProdutoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(692, Short.MAX_VALUE))
        );
        jInternalFrameCadastroProdutoLayout.setVerticalGroup(
            jInternalFrameCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameCadastroProdutoLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jInternalFrameCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCadastroProdutoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCadastroProdutoNome))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastroProdutopreco)
                    .addComponent(jTextFieldCadastroProdutoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastroProdutoSalvar)
                    .addComponent(jButtonCadastroProdutoCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jInternalFramePesquisar.setTitle("Pesquisar pelo Nome");
        jInternalFramePesquisar.setVisible(true);

        jTablePesquisarPorNome.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTablePesquisarPorNome);

        jLabel1.setText("Selecione a ação desejada");

        jLabel2.setText("Qual o ID do produto");

        jComboBoxPesquisarAcao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Editar", "Excluir", "Adicionar no Carrinho", " " }));

        jButtonPesquisarConfirmar.setText("Confirmar");
        jButtonPesquisarConfirmar.addActionListener(this::jButtonPesquisarConfirmarActionPerformed);

        jButtonPesquisarCancelar.setText("Cancelar");
        jButtonPesquisarCancelar.addActionListener(this::jButtonPesquisarCancelarActionPerformed);

        jLabelPesquisarQuantidade.setText("Quantidade");

        javax.swing.GroupLayout jInternalFramePesquisarLayout = new javax.swing.GroupLayout(jInternalFramePesquisar.getContentPane());
        jInternalFramePesquisar.getContentPane().setLayout(jInternalFramePesquisarLayout);
        jInternalFramePesquisarLayout.setHorizontalGroup(
            jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFramePesquisarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
                    .addGroup(jInternalFramePesquisarLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabelPesquisarQuantidade))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxPesquisarAcao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldPesquisarID)
                            .addComponent(jTextFieldPesquizarQuantidade))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFramePesquisarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonPesquisarConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPesquisarCancelar)
                .addGap(15, 15, 15))
        );
        jInternalFramePesquisarLayout.setVerticalGroup(
            jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFramePesquisarLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxPesquisarAcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPesquisarID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPesquisarQuantidade)
                    .addComponent(jTextFieldPesquizarQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPesquisarConfirmar)
                    .addComponent(jButtonPesquisarCancelar))
                .addGap(14, 14, 14))
        );

        jInternalFrameEditarCadastro.setTitle("Edição de Cadastro");
        jInternalFrameEditarCadastro.setVisible(true);

        jLabel3.setText("Nome do Produto");

        jLabel4.setText("Preço");

        jLabel5.setText("ID:");

        jTextFieldEditarId.setEnabled(false);

        jButtonEditarSalvar.setText("salvar");
        jButtonEditarSalvar.addActionListener(this::jButtonEditarSalvarActionPerformed);

        jButtonEditarCancelar.setText("Cancelar");
        jButtonEditarCancelar.addActionListener(this::jButtonEditarCancelarActionPerformed);

        javax.swing.GroupLayout jInternalFrameEditarCadastroLayout = new javax.swing.GroupLayout(jInternalFrameEditarCadastro.getContentPane());
        jInternalFrameEditarCadastro.getContentPane().setLayout(jInternalFrameEditarCadastroLayout);
        jInternalFrameEditarCadastroLayout.setHorizontalGroup(
            jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameEditarCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jInternalFrameEditarCadastroLayout.createSequentialGroup()
                        .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(35, 35, 35)
                        .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldEditarNome)
                                .addComponent(jTextFieldEditarPreco, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE))
                            .addComponent(jTextFieldEditarId, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jInternalFrameEditarCadastroLayout.createSequentialGroup()
                        .addComponent(jButtonEditarSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEditarCancelar)))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jInternalFrameEditarCadastroLayout.setVerticalGroup(
            jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameEditarCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldEditarId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldEditarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldEditarPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEditarSalvar)
                    .addComponent(jButtonEditarCancelar))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(jInternalFrameCadastroProduto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jInternalFramePesquisar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jInternalFrameEditarCadastro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrameCadastroProduto)
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jInternalFramePesquisar)
                    .addContainerGap()))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addGap(246, 246, 246)
                    .addComponent(jInternalFrameEditarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(246, Short.MAX_VALUE)))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jInternalFrameCadastroProduto)
                .addGap(0, 0, 0))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jInternalFramePesquisar)
                    .addContainerGap()))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addGap(189, 189, 189)
                    .addComponent(jInternalFrameEditarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(189, Short.MAX_VALUE)))
        );

        jMenuCadastro.setText("Cadastro");

        jMenuItemCadastroProduto.setText("Produto");
        jMenuItemCadastroProduto.addActionListener(this::jMenuItemCadastroProdutoActionPerformed);
        jMenuCadastro.add(jMenuItemCadastroProduto);

        jMenuBarPrincipal.add(jMenuCadastro);

        jMenuEdicao.setText("Edição");

        jMenuItemEdicaoProduto.setText("Produto");
        jMenuItemEdicaoProduto.addActionListener(this::jMenuItemEdicaoProdutoActionPerformed);
        jMenuEdicao.add(jMenuItemEdicaoProduto);

        jMenuBarPrincipal.add(jMenuEdicao);

        jMenuPesquisar.setText("Pesquisar");
        jMenuPesquisar.addActionListener(this::jMenuPesquisarActionPerformed);

        jMenuItemPesquisarProduto.setText("Produto");
        jMenuItemPesquisarProduto.addActionListener(this::jMenuItemPesquisarProdutoActionPerformed);
        jMenuPesquisar.add(jMenuItemPesquisarProduto);

        jMenuBarPrincipal.add(jMenuPesquisar);

        jMenuVendas.setText("Vendas");

        jMenuItemVendasCarrinho.setText("Carrinho");
        jMenuVendas.add(jMenuItemVendasCarrinho);

        jMenuBarPrincipal.add(jMenuVendas);

        setJMenuBar(jMenuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroProdutoActionPerformed
        jInternalFrameCadastroProduto.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastroProdutoActionPerformed

    private void jButtonCadastroProdutoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroProdutoCancelarActionPerformed
        // TODO add your handling code here:
        jTextFieldCadastroProdutoNome.setText("");
        jTextFieldCadastroProdutoPreco.setText("");
        jInternalFrameCadastroProduto.setVisible(false);
    }//GEN-LAST:event_jButtonCadastroProdutoCancelarActionPerformed

    private void jButtonCadastroProdutoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroProdutoSalvarActionPerformed
        // TODO add your handling code here:
        String nome = jTextFieldCadastroProdutoNome.getText();
        
        if (nome.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "O campo nome do produto esta vazio");
         
        } else {
        
        String preco = jTextFieldCadastroProdutoPreco.getText();
        
        if (preco.equals("")){
            JOptionPane.showMessageDialog(rootPane, "O campo preço do produto esta vazio");
        } else {
            try {
                double precoConvertido = Double.parseDouble(preco);
                Produto produto = new Produto(nome, precoConvertido);
                produto.apresentarProduto();
                produto.salvar(nome, precoConvertido);
                
                
                
                jTextFieldCadastroProdutoNome.setText("");
                jTextFieldCadastroProdutoPreco.setText("");
                
                JOptionPane.showMessageDialog(rootPane, "O produto "+nome+" foi cadastrado com sucesso");
                jInternalFrameCadastroProduto.setVisible(false);
        } catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, "O valor do Produto deve ser prenchido com ponto");
            }
           }
        }
    }//GEN-LAST:event_jButtonCadastroProdutoSalvarActionPerformed

    private void jMenuItemPesquisarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPesquisarProdutoActionPerformed
        // TODO add your handling code here:
        String nome = JOptionPane.showInputDialog("Informe o Nome: ");
        Produto produto = new Produto();
        ArrayList<Produto> produtos = produto.pesquisar(nome);
        
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Nome");
        modelo.addColumn("Preço");
        
        for(Produto produtoAux: produtos){
          modelo.addRow(new Object[]{produtoAux.getId(), produtoAux.getNome(), produtoAux.getPreco()});
          jTablePesquisarPorNome.setModel(modelo);
        }
        
        jInternalFramePesquisar.setVisible(true);
    }//GEN-LAST:event_jMenuItemPesquisarProdutoActionPerformed

    private void jButtonPesquisarConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarConfirmarActionPerformed
        // TODO add your handling code here:
        Produto produto = new Produto();
        String opcao = jComboBoxPesquisarAcao.getSelectedItem().toString();
        System.out.println("Opção selecionada"+opcao);
        
        int idPesquisar = Integer.parseInt(jTextFieldPesquisarID.getText());
        System.out.println("ID Informado"+idPesquisar);
        if (opcao.equals("Excluir")) {
            produto.deletar(idPesquisar);
            JOptionPane.showMessageDialog(rootPane,"Oproduto de ID: "+idPesquisar+" foi excluido com sucesso"
            );
            
            jComboBoxPesquisarAcao.setSelectedIndex(0);
            jTextFieldPesquisarID.setText("");
            jInternalFramePesquisar.setVisible(false);
            
        } else if(opcao.equals("Editar")) {//editar
             jInternalFramePesquisar.setVisible(false);
             
             Produto produtoRecuperado = produto.buscarPorId(idPesquisar);
             
             jTextFieldEditarId.setText(idPesquisar+"");
             jTextFieldEditarNome.setText(produtoRecuperado.getNome());
             jTextFieldEditarPreco.setText(produtoRecuperado.getPreco()+"");
             jInternalFrameEditarCadastro.setVisible(true);
        } else if(opcao.equals("Adicionar no carrinho")) {//adicionar no carrinho
            JOptionPane.showMessageDialog(rootPane,"O produto foi adicionado ao carrinho ");
            jTextFieldPesquisarID.setText("");
            jComboBoxPesquisarAcao.setSelectedIndex(0);
            jInternalFramePesquisar.setVisible(false);
            
    }//GEN-LAST:event_jButtonPesquisarConfirmarActionPerformed
 }
    private void jButtonPesquisarCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarCancelarActionPerformed
        // TODO add your handling code here:
        jTextFieldPesquisarID.setText("");
        jComboBoxPesquisarAcao.setSelectedIndex(0);
        jInternalFramePesquisar.setVisible(false);
    }//GEN-LAST:event_jButtonPesquisarCancelarActionPerformed

    private void jButtonEditarSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarSalvarActionPerformed
        // TODO add your handling code here:
        String nome = jTextFieldEditarNome.getText();
        double preco = Double.parseDouble(jTextFieldEditarPreco.getText());
        int id = Integer.parseInt(jTextFieldEditarId.getText());
        
        Produto produto = new Produto();
        produto.editar(nome,preco,id);
        
        jTextFieldEditarId.setText("");
        jTextFieldEditarNome.setText("");
        jTextFieldEditarPreco.setText("");
        
        JOptionPane.showMessageDialog(rootPane, "Produto atualizado com Sucesso");
        
        jInternalFrameEditarCadastro.setVisible(false);
        
    }//GEN-LAST:event_jButtonEditarSalvarActionPerformed

    private void jButtonEditarCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarCancelarActionPerformed
        // TODO add your handling code here:
        jTextFieldEditarId.setText("");
        jTextFieldEditarNome.setText("");
        jTextFieldEditarPreco.setText("");
        
        jInternalFrameEditarCadastro.setVisible(false);
    }//GEN-LAST:event_jButtonEditarCancelarActionPerformed

    private void jMenuPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuPesquisarActionPerformed

    private void jMenuItemEdicaoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEdicaoProdutoActionPerformed
        // TODO add your handling code here:
        String nome = JOptionPane.showInputDialog("Informe o Nome: ");
        Produto produto = new Produto();
        ArrayList<Produto> produtos = produto.pesquisar(nome);
        
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Nome");
        modelo.addColumn("Preço");
        
        for(Produto produtoAux: produtos){
          modelo.addRow(new Object[]{produtoAux.getId(), produtoAux.getNome(), produtoAux.getPreco()});
          jTablePesquisarPorNome.setModel(modelo);
        }
        
        jInternalFramePesquisar.setVisible(true);
    }//GEN-LAST:event_jMenuItemEdicaoProdutoActionPerformed

    public JInternalFrame getjInternalFrameEditarCadastro () {
      return jInternalFrameEditarCadastro;
    }
    /**
     * @param args the command line arguments
     */
    
  public JInternalFrame getjInternalFrameCadastroProduto(){
  return jInternalFrameCadastroProduto;
  }
  
  public JInternalFrame getjInternalFramePesquisar() {
      return jInternalFramePesquisar;
  }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastroProdutoCancelar;
    private javax.swing.JButton jButtonCadastroProdutoSalvar;
    private javax.swing.JButton jButtonEditarCancelar;
    private javax.swing.JButton jButtonEditarSalvar;
    private javax.swing.JButton jButtonPesquisarCancelar;
    private javax.swing.JButton jButtonPesquisarConfirmar;
    private javax.swing.JComboBox<String> jComboBoxPesquisarAcao;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JInternalFrame jInternalFrameCadastroProduto;
    private javax.swing.JInternalFrame jInternalFrameEditarCadastro;
    private javax.swing.JInternalFrame jInternalFramePesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelCadastroProdutoNome;
    private javax.swing.JLabel jLabelCadastroProdutopreco;
    private javax.swing.JLabel jLabelPesquisarQuantidade;
    private javax.swing.JMenuBar jMenuBarPrincipal;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuEdicao;
    private javax.swing.JMenuItem jMenuItemCadastroProduto;
    private javax.swing.JMenuItem jMenuItemEdicaoProduto;
    private javax.swing.JMenuItem jMenuItemPesquisarProduto;
    private javax.swing.JMenuItem jMenuItemVendasCarrinho;
    private javax.swing.JMenu jMenuPesquisar;
    private javax.swing.JMenu jMenuVendas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePesquisarPorNome;
    private javax.swing.JTextField jTextFieldCadastroProdutoNome;
    private javax.swing.JTextField jTextFieldCadastroProdutoPreco;
    private javax.swing.JTextField jTextFieldEditarId;
    private javax.swing.JTextField jTextFieldEditarNome;
    private javax.swing.JTextField jTextFieldEditarPreco;
    private javax.swing.JTextField jTextFieldPesquisarID;
    private javax.swing.JTextField jTextFieldPesquizarQuantidade;
    // End of variables declaration//GEN-END:variables
}
