/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.projeto2.barelanchonete.view;

import br.com.projeto2.barelanchonete.model.Produto;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author sluiz
 */
public class GUIMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIMenu.class.getName());

    /**
     * Creates new form GUIMenu
     */
    public GUIMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jInternalFrameCadastroProduto = new javax.swing.JInternalFrame();
        jLabelCadastroProdutoNome = new javax.swing.JLabel();
        jTextFieldCadastroProdutoNome = new javax.swing.JTextField();
        jLabelCadastroProdutopreco = new javax.swing.JLabel();
        jTextFieldCadastroProdutoPreco = new javax.swing.JTextField();
        jButtonCadastroProdutoSalvar = new javax.swing.JButton();
        jButtonCadastroProdutoCancelar = new javax.swing.JButton();
        jMenuBarPrincipal = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemCadastroProduto = new javax.swing.JMenuItem();
        jMenuEdicao = new javax.swing.JMenu();
        jMenuItemEdicaoProduto = new javax.swing.JMenuItem();
        jMenuPesquisar = new javax.swing.JMenu();
        jMenuItemPesquisarProduto = new javax.swing.JMenuItem();
        jMenuVendas = new javax.swing.JMenu();
        jMenuItemVendasCarrinho = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Bar e Lanchonete");

        jInternalFrameCadastroProduto.setBackground(new java.awt.Color(0, 51, 255));
        jInternalFrameCadastroProduto.setTitle("Cadastro de Produto");
        jInternalFrameCadastroProduto.setVisible(true);

        jLabelCadastroProdutoNome.setText("Nome do Produto");

        jLabelCadastroProdutopreco.setText("Preço");

        jButtonCadastroProdutoSalvar.setText("Salvar");
        jButtonCadastroProdutoSalvar.addActionListener(this::jButtonCadastroProdutoSalvarActionPerformed);

        jButtonCadastroProdutoCancelar.setText("Cancelar");
        jButtonCadastroProdutoCancelar.addActionListener(this::jButtonCadastroProdutoCancelarActionPerformed);

        javax.swing.GroupLayout jInternalFrameCadastroProdutoLayout = new javax.swing.GroupLayout(jInternalFrameCadastroProduto.getContentPane());
        jInternalFrameCadastroProduto.getContentPane().setLayout(jInternalFrameCadastroProdutoLayout);
        jInternalFrameCadastroProdutoLayout.setHorizontalGroup(
            jInternalFrameCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameCadastroProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrameCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jInternalFrameCadastroProdutoLayout.createSequentialGroup()
                        .addComponent(jButtonCadastroProdutoSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCadastroProdutoCancelar))
                    .addGroup(jInternalFrameCadastroProdutoLayout.createSequentialGroup()
                        .addGroup(jInternalFrameCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCadastroProdutoNome)
                            .addComponent(jLabelCadastroProdutopreco))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrameCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCadastroProdutoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCadastroProdutoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jInternalFrameCadastroProdutoLayout.setVerticalGroup(
            jInternalFrameCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameCadastroProdutoLayout.createSequentialGroup()
                .addGroup(jInternalFrameCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCadastroProdutoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCadastroProdutoNome))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastroProdutopreco)
                    .addComponent(jTextFieldCadastroProdutoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastroProdutoSalvar)
                    .addComponent(jButtonCadastroProdutoCancelar))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(jInternalFrameCadastroProduto, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrameCadastroProduto)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jInternalFrameCadastroProduto)
                .addGap(0, 0, 0))
        );

        jMenuCadastro.setText("Cadastro");

        jMenuItemCadastroProduto.setText("Produto");
        jMenuItemCadastroProduto.addActionListener(this::jMenuItemCadastroProdutoActionPerformed);
        jMenuCadastro.add(jMenuItemCadastroProduto);

        jMenuBarPrincipal.add(jMenuCadastro);

        jMenuEdicao.setText("Edição");

        jMenuItemEdicaoProduto.setText("Produto");
        jMenuEdicao.add(jMenuItemEdicaoProduto);

        jMenuBarPrincipal.add(jMenuEdicao);

        jMenuPesquisar.setText("Pesquisar");

        jMenuItemPesquisarProduto.setText("Produto");
        jMenuPesquisar.add(jMenuItemPesquisarProduto);

        jMenuBarPrincipal.add(jMenuPesquisar);

        jMenuVendas.setText("Vendas");

        jMenuItemVendasCarrinho.setText("Carrinho");
        jMenuVendas.add(jMenuItemVendasCarrinho);

        jMenuBarPrincipal.add(jMenuVendas);

        setJMenuBar(jMenuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroProdutoActionPerformed
        jInternalFrameCadastroProduto.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastroProdutoActionPerformed

    private void jButtonCadastroProdutoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroProdutoCancelarActionPerformed
        // TODO add your handling code here:
        jTextFieldCadastroProdutoNome.setText("");
        jTextFieldCadastroProdutoPreco.setText("");
        jInternalFrameCadastroProduto.setVisible(false);
    }//GEN-LAST:event_jButtonCadastroProdutoCancelarActionPerformed

    private void jButtonCadastroProdutoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroProdutoSalvarActionPerformed
        // TODO add your handling code here:
        String nome = jTextFieldCadastroProdutoNome.getText();
        
        if (nome.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "O campo nome do produto esta vazio");
         
        } else {
        
        String preco = jTextFieldCadastroProdutoPreco.getText();
        
        if (preco.equals("")){
            JOptionPane.showMessageDialog(rootPane, "O campo preço do produto esta vazio");
        } else {
            try {
                double precoConvertido = Double.parseDouble(preco);
                Produto produto = new Produto(nome, precoConvertido);
                produto.apresentarProduto();
                
                
                
                jTextFieldCadastroProdutoNome.setText("");
                jTextFieldCadastroProdutoPreco.setText("");
                
                JOptionPane.showMessageDialog(rootPane, "O produto "+nome+" foi cadastrado com sucesso");
                jInternalFrameCadastroProduto.setVisible(false);
        } catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, "O valor do Produto deve ser prenchido com ponto");
            }
           }
        }
    }//GEN-LAST:event_jButtonCadastroProdutoSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    
  public JInternalFrame getjInternalFrameCadastroProduto(){
  return jInternalFrameCadastroProduto;
  }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastroProdutoCancelar;
    private javax.swing.JButton jButtonCadastroProdutoSalvar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JInternalFrame jInternalFrameCadastroProduto;
    private javax.swing.JLabel jLabelCadastroProdutoNome;
    private javax.swing.JLabel jLabelCadastroProdutopreco;
    private javax.swing.JMenuBar jMenuBarPrincipal;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuEdicao;
    private javax.swing.JMenuItem jMenuItemCadastroProduto;
    private javax.swing.JMenuItem jMenuItemEdicaoProduto;
    private javax.swing.JMenuItem jMenuItemPesquisarProduto;
    private javax.swing.JMenuItem jMenuItemVendasCarrinho;
    private javax.swing.JMenu jMenuPesquisar;
    private javax.swing.JMenu jMenuVendas;
    private javax.swing.JTextField jTextFieldCadastroProdutoNome;
    private javax.swing.JTextField jTextFieldCadastroProdutoPreco;
    // End of variables declaration//GEN-END:variables
}
